name: tests
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - run: python -m pip install -U pip
      # Ставим dev-экстры, а если их нет в pyproject — запасной путь
      - run: pip install -e ".[dev]" || pip install pytest hypothesis httpx "uvicorn[standard]" fastapi typer "pydantic>=2" tqdm
      - run: pytest -q
